blueprint:
  name: AI Event Summary with Keywords (v1.4.2)
  author: valentinfrlch, adnansarajlic
  description: >
    AI-powered summaries for security camera events.
    Sends a notification with a preview to your phone that is updated dynamically when the AI summary is available.
    Includes keyword-based notification triggering.
  domain: automation
  source_url: https://github.com/valentinfrlch/ha-llmvision/blob/main/blueprints/event_summary_keywords.yaml
  input:
    important:
      name: Important (Experimental)
      description: >
        Use AI to classify events as Critical, Normal or Low.
        Notifications are sent only for events classified as Normal or higher.
        Critical events override 'Do Not Disturb' settings.
        Use with caution: AI can make mistakes.
      default: false
      selector:
        boolean:
    remember:
      name: Remember
      description: Stores this event in the Timeline so you can ask about it. If important is enabled, only events classified as Normal or Critical will be saved.
      default: false
      selector:
        boolean:
    use_memory:
      name: Use Memory
      description: 'Use information stored in memory to provide additional context. Memory must be set up.'
      default: false
      selector:
        boolean:
    message:
      name: Prompt
      description: Model prompt for the video_analyzer action
      default: "Summarize the events based on a series of images captured at short intervals. Focus only on moving subjects such as people, vehicles, and other active elements. Ignore static objects and scenery. Provide a clear and concise account of movements and interactions. Do not mention or imply the existence of images. Present the information as if directly observing the events. If no movement is detected, respond with: 'No activity observed.'"
      selector:
        text:
          multiline: true
    trigger_keywords:
      name: Trigger Keywords
      description: Enter keywords (comma-separated) that will trigger notifications regardless of importance setting. For example person, car, package, delivery
      default: ""
      selector:
        text:
          multiline: false
    notification_delivery:
      name: Notification Delivery
      default: 'Dynamic'
      selector:
        select:
          options:
            - Dynamic
            - Consolidated

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ preview_mode=='Snapshot' }}"
        sequence:
        - alias: "(Snapshot) Update notification on notify devices"
          repeat:
            for_each: "{{device_name_map}}"
            sequence:
              - action: "notify.{{ repeat.item }}"
                data:
                  title: "{{ label }}"
                  message: "{{response.response_text}}"
                  data:
                    image: "{{response.key_frame.replace('/config/www/','/local/') }}"
                    url: !input tap_navigate #iOS
                    clickAction: !input tap_navigate #Android
                    tag: "{{tag}}"
                    group: "{{group}}"
                    push:
                      interruption-level: "{{'passive' if notification_delivery=='Dynamic' else 'active'}}"
                    style: big_text
                    big_text: "{{response.response_text}}"
      - conditions:
          - condition: template
            value_template: "{{ preview_mode=='Live Preview' }}"
        sequence:
        - alias: "(Live Preview) Update notification on notify devices"
          repeat:
            for_each: "{{device_name_map}}"
            sequence:
              - action: "notify.{{ repeat.item }}"
                data:
                  title: "{{ label }}"
                  message: "{{response.response_text}}"
                  data:
                    entity_id: "{{camera_entity}}"
                    url: !input tap_navigate #iOS
                    clickAction: !input tap_navigate #Android
                    tag: "{{tag}}"
                    group: "{{group}}"
                    push:
                      interruption-level: "{{'passive' if notification_delivery=='Dynamic' else 'active'}}"
                    style: big_text
                    big_text: "{{response.response_text}}"
  
  - delay: '00:{{cooldown|int}}:00'
